### ISSUE TITLE
Termux X11 instead of VNC

### ISSUE THREAD

**Issue by ryangp** [23xvx/Termux-Ubuntu-Installer#1]
how can i export the display in termux x11 instead of vnc?

**Comment by 23xvx** [comment]
Which desktop have you installed?

**Comment by ryangp** [comment]
> Which desktop have you installed?

im using ubuntu.

but it is possible to have this option in all desktop environment?. Thanks

**Comment by 23xvx** [comment]
I will write a doc to give the instructions

**Comment by ryangp** [comment]
> I will write a doc to give the instructions

ohh man.. thank you

**Comment by 23xvx** [comment]
check [USAGE.md](https://github.com/23xvx/termux-ubuntu-installer/blob/main/USAGE.md)
