### ISSUE TITLE
CRASHED WHEN CLICKING

### ISSUE THREAD

**Issue by ryangp** [23xvx/Termux-Ubuntu-Installer#3]
![Screenshot_20241011_092322_com termux](https://github.com/user-attachments/assets/26f659fd-2ab3-44b3-92f1-9e9478ec936b)

https://github.com/user-attachments/assets/f69aaf93-f79f-4c11-8586-3b65ccbb6559

When i click on workspace. the system crashed.

**Comment by 23xvx** [comment]
What happened after pressing the log out button?

**Comment by ryangp** [comment]
> What happened after pressing the log out button?
the vnc closes. and when i try to vncstaart again in termux and open the vnc viewer...after clicking it goess like that again...it repeating. i cant use it.

**Comment by 23xvx** [comment]
Try this before `vncstart`
```bash
sed -i 's/gnome-session/gnome-shell/g' ~/.vnc/xstartup
```
