### ISSUE TITLE
Problem with installing WINE

### ISSUE THREAD

**Issue by ryangp** [23xvx/Termux-Ubuntu-Installer#5]
I was about to install Wine, but o always have a problem woth win32:i386 is missing. I tried all the possible solution over the internet but i have no luck of fixing it.

I hope you can help me. Thank you

**Comment by 23xvx** [comment]
Never try to install wine directly using apt in termux.
Wine does not work on arm64 without special setups.

To install wine in ubuntu, you can find documents on https://github.com/cheadrian/termux-chroot-proot-wine-box86_64.git
They have clear instructions on installing wine
